/*
 * generated by Xtext 2.32.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.ide;


/**
 * Use this class to register ide components.
 */
public class QueryIdeModule extends AbstractQueryIdeModule {
}
