/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getBooleanPredicate()
 * @model
 * @generated
 */
public interface BooleanPredicate extends EObject
{
} // BooleanPredicate
