/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.EntityExpression#getSelectedEntity <em>Selected Entity</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.EntityExpression#getEje <em>Eje</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getEntityExpression()
 * @model
 * @generated
 */
public interface EntityExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Selected Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selected Entity</em>' containment reference.
   * @see #setSelectedEntity(SelectedEntity)
   * @see com.epistimis.uddl.query.query.QueryPackage#getEntityExpression_SelectedEntity()
   * @model containment="true"
   * @generated
   */
  SelectedEntity getSelectedEntity();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.EntityExpression#getSelectedEntity <em>Selected Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selected Entity</em>' containment reference.
   * @see #getSelectedEntity()
   * @generated
   */
  void setSelectedEntity(SelectedEntity value);

  /**
   * Returns the value of the '<em><b>Eje</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.query.query.EntityJoinExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eje</em>' containment reference list.
   * @see com.epistimis.uddl.query.query.QueryPackage#getEntityExpression_Eje()
   * @model containment="true"
   * @generated
   */
  EList<EntityJoinExpression> getEje();

} // EntityExpression
