/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Literal Reference Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.EnumLiteralReferenceExpression#getTyp <em>Typ</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.EnumLiteralReferenceExpression#getLiteral <em>Literal</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getEnumLiteralReferenceExpression()
 * @model
 * @generated
 */
public interface EnumLiteralReferenceExpression extends PredicateTerm
{
  /**
   * Returns the value of the '<em><b>Typ</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typ</em>' containment reference.
   * @see #setTyp(EnumerationTypeReference)
   * @see com.epistimis.uddl.query.query.QueryPackage#getEnumLiteralReferenceExpression_Typ()
   * @model containment="true"
   * @generated
   */
  EnumerationTypeReference getTyp();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.EnumLiteralReferenceExpression#getTyp <em>Typ</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typ</em>' containment reference.
   * @see #getTyp()
   * @generated
   */
  void setTyp(EnumerationTypeReference value);

  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference.
   * @see #setLiteral(EnumerationLiteralReference)
   * @see com.epistimis.uddl.query.query.QueryPackage#getEnumLiteralReferenceExpression_Literal()
   * @model containment="true"
   * @generated
   */
  EnumerationLiteralReference getLiteral();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.EnumLiteralReferenceExpression#getLiteral <em>Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' containment reference.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(EnumerationLiteralReference value);

} // EnumLiteralReferenceExpression
