/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Explicit Selected Entity Characteristic Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.ExplicitSelectedEntityCharacteristicReference#getSelectedEntityCharacteristicReference <em>Selected Entity Characteristic Reference</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.ExplicitSelectedEntityCharacteristicReference#getProjectedCharacteristicAlias <em>Projected Characteristic Alias</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getExplicitSelectedEntityCharacteristicReference()
 * @model
 * @generated
 */
public interface ExplicitSelectedEntityCharacteristicReference extends ProjectedCharacteristicExpression
{
  /**
   * Returns the value of the '<em><b>Selected Entity Characteristic Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selected Entity Characteristic Reference</em>' containment reference.
   * @see #setSelectedEntityCharacteristicReference(SelectedEntityCharacteristicReference)
   * @see com.epistimis.uddl.query.query.QueryPackage#getExplicitSelectedEntityCharacteristicReference_SelectedEntityCharacteristicReference()
   * @model containment="true"
   * @generated
   */
  SelectedEntityCharacteristicReference getSelectedEntityCharacteristicReference();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.ExplicitSelectedEntityCharacteristicReference#getSelectedEntityCharacteristicReference <em>Selected Entity Characteristic Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selected Entity Characteristic Reference</em>' containment reference.
   * @see #getSelectedEntityCharacteristicReference()
   * @generated
   */
  void setSelectedEntityCharacteristicReference(SelectedEntityCharacteristicReference value);

  /**
   * Returns the value of the '<em><b>Projected Characteristic Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projected Characteristic Alias</em>' containment reference.
   * @see #setProjectedCharacteristicAlias(ProjectedCharacteristicAlias)
   * @see com.epistimis.uddl.query.query.QueryPackage#getExplicitSelectedEntityCharacteristicReference_ProjectedCharacteristicAlias()
   * @model containment="true"
   * @generated
   */
  ProjectedCharacteristicAlias getProjectedCharacteristicAlias();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.ExplicitSelectedEntityCharacteristicReference#getProjectedCharacteristicAlias <em>Projected Characteristic Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projected Characteristic Alias</em>' containment reference.
   * @see #getProjectedCharacteristicAlias()
   * @generated
   */
  void setProjectedCharacteristicAlias(ProjectedCharacteristicAlias value);

} // ExplicitSelectedEntityCharacteristicReference
