/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ordering Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.OrderingExpression#getCharacteristic <em>Characteristic</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.OrderingExpression#getOrderingType <em>Ordering Type</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getOrderingExpression()
 * @model
 * @generated
 */
public interface OrderingExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Characteristic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Characteristic</em>' containment reference.
   * @see #setCharacteristic(ProjectedCharacteristicReference)
   * @see com.epistimis.uddl.query.query.QueryPackage#getOrderingExpression_Characteristic()
   * @model containment="true"
   * @generated
   */
  ProjectedCharacteristicReference getCharacteristic();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.OrderingExpression#getCharacteristic <em>Characteristic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Characteristic</em>' containment reference.
   * @see #getCharacteristic()
   * @generated
   */
  void setCharacteristic(ProjectedCharacteristicReference value);

  /**
   * Returns the value of the '<em><b>Ordering Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ordering Type</em>' attribute.
   * @see #setOrderingType(String)
   * @see com.epistimis.uddl.query.query.QueryPackage#getOrderingExpression_OrderingType()
   * @model
   * @generated
   */
  String getOrderingType();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.OrderingExpression#getOrderingType <em>Ordering Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ordering Type</em>' attribute.
   * @see #getOrderingType()
   * @generated
   */
  void setOrderingType(String value);

} // OrderingExpression
