/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Order By Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.OrderByClause#getOrderingExpression <em>Ordering Expression</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getOrderByClause()
 * @model
 * @generated
 */
public interface OrderByClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Ordering Expression</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.query.query.OrderingExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ordering Expression</em>' containment reference list.
   * @see com.epistimis.uddl.query.query.QueryPackage#getOrderByClause_OrderingExpression()
   * @model containment="true"
   * @generated
   */
  EList<OrderingExpression> getOrderingExpression();

} // OrderByClause
