/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.QueryStatement#getQualifier <em>Qualifier</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.QueryStatement#getProjectedCharacteristicList <em>Projected Characteristic List</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.QueryStatement#getSelectedEntityExpression <em>Selected Entity Expression</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getQueryStatement()
 * @model
 * @generated
 */
public interface QueryStatement extends QuerySpecification
{
  /**
   * Returns the value of the '<em><b>Qualifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualifier</em>' attribute.
   * @see #setQualifier(String)
   * @see com.epistimis.uddl.query.query.QueryPackage#getQueryStatement_Qualifier()
   * @model
   * @generated
   */
  String getQualifier();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.QueryStatement#getQualifier <em>Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qualifier</em>' attribute.
   * @see #getQualifier()
   * @generated
   */
  void setQualifier(String value);

  /**
   * Returns the value of the '<em><b>Projected Characteristic List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projected Characteristic List</em>' containment reference.
   * @see #setProjectedCharacteristicList(ProjectedCharacteristicList)
   * @see com.epistimis.uddl.query.query.QueryPackage#getQueryStatement_ProjectedCharacteristicList()
   * @model containment="true"
   * @generated
   */
  ProjectedCharacteristicList getProjectedCharacteristicList();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.QueryStatement#getProjectedCharacteristicList <em>Projected Characteristic List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projected Characteristic List</em>' containment reference.
   * @see #getProjectedCharacteristicList()
   * @generated
   */
  void setProjectedCharacteristicList(ProjectedCharacteristicList value);

  /**
   * Returns the value of the '<em><b>Selected Entity Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selected Entity Expression</em>' containment reference.
   * @see #setSelectedEntityExpression(SelectedEntityExpression)
   * @see com.epistimis.uddl.query.query.QueryPackage#getQueryStatement_SelectedEntityExpression()
   * @model containment="true"
   * @generated
   */
  SelectedEntityExpression getSelectedEntityExpression();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.QueryStatement#getSelectedEntityExpression <em>Selected Entity Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selected Entity Expression</em>' containment reference.
   * @see #getSelectedEntityExpression()
   * @generated
   */
  void setSelectedEntityExpression(SelectedEntityExpression value);

} // QueryStatement
