/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.QueryIdentifier#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getQueryIdentifier()
 * @model
 * @generated
 */
public interface QueryIdentifier extends SelectedEntityReference, UnqualifiedProjectedCharacteristicReferenceOrAlias, CharacteristicReference, EntityTypeReference, EnumerationTypeReference, EnumerationLiteralReference, SelectedEntityAlias, ProjectedCharacteristicAlias
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see com.epistimis.uddl.query.query.QueryPackage#getQueryIdentifier_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.QueryIdentifier#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

} // QueryIdentifier
