/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selected Entity Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.SelectedEntityExpression#getFrom <em>From</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.SelectedEntityExpression#getWhere <em>Where</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.SelectedEntityExpression#getOrderBy <em>Order By</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getSelectedEntityExpression()
 * @model
 * @generated
 */
public interface SelectedEntityExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' containment reference.
   * @see #setFrom(FromClause)
   * @see com.epistimis.uddl.query.query.QueryPackage#getSelectedEntityExpression_From()
   * @model containment="true"
   * @generated
   */
  FromClause getFrom();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.SelectedEntityExpression#getFrom <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' containment reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(FromClause value);

  /**
   * Returns the value of the '<em><b>Where</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where</em>' containment reference.
   * @see #setWhere(WhereClause)
   * @see com.epistimis.uddl.query.query.QueryPackage#getSelectedEntityExpression_Where()
   * @model containment="true"
   * @generated
   */
  WhereClause getWhere();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.SelectedEntityExpression#getWhere <em>Where</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Where</em>' containment reference.
   * @see #getWhere()
   * @generated
   */
  void setWhere(WhereClause value);

  /**
   * Returns the value of the '<em><b>Order By</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order By</em>' containment reference.
   * @see #setOrderBy(OrderByClause)
   * @see com.epistimis.uddl.query.query.QueryPackage#getSelectedEntityExpression_OrderBy()
   * @model containment="true"
   * @generated
   */
  OrderByClause getOrderBy();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.SelectedEntityExpression#getOrderBy <em>Order By</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order By</em>' containment reference.
   * @see #getOrderBy()
   * @generated
   */
  void setOrderBy(OrderByClause value);

} // SelectedEntityExpression
