/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selected Entity Characteristic Wildcard Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.SelectedEntityCharacteristicWildcardReference#getSelectedEntity <em>Selected Entity</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getSelectedEntityCharacteristicWildcardReference()
 * @model
 * @generated
 */
public interface SelectedEntityCharacteristicWildcardReference extends ProjectedCharacteristicExpression
{
  /**
   * Returns the value of the '<em><b>Selected Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selected Entity</em>' containment reference.
   * @see #setSelectedEntity(SelectedEntityReference)
   * @see com.epistimis.uddl.query.query.QueryPackage#getSelectedEntityCharacteristicWildcardReference_SelectedEntity()
   * @model containment="true"
   * @generated
   */
  SelectedEntityReference getSelectedEntity();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.SelectedEntityCharacteristicWildcardReference#getSelectedEntity <em>Selected Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selected Entity</em>' containment reference.
   * @see #getSelectedEntity()
   * @generated
   */
  void setSelectedEntity(SelectedEntityReference value);

} // SelectedEntityCharacteristicWildcardReference
