/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set Membership Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.SetMembershipPredicate#getLeft <em>Left</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.SetMembershipPredicate#isNot <em>Not</em>}</li>
 *   <li>{@link com.epistimis.uddl.query.query.SetMembershipPredicate#getSet <em>Set</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getSetMembershipPredicate()
 * @model
 * @generated
 */
public interface SetMembershipPredicate extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(PredicateTerm)
   * @see com.epistimis.uddl.query.query.QueryPackage#getSetMembershipPredicate_Left()
   * @model containment="true"
   * @generated
   */
  PredicateTerm getLeft();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.SetMembershipPredicate#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(PredicateTerm value);

  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(boolean)
   * @see com.epistimis.uddl.query.query.QueryPackage#getSetMembershipPredicate_Not()
   * @model
   * @generated
   */
  boolean isNot();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.SetMembershipPredicate#isNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #isNot()
   * @generated
   */
  void setNot(boolean value);

  /**
   * Returns the value of the '<em><b>Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set</em>' containment reference.
   * @see #setSet(LogicalSet)
   * @see com.epistimis.uddl.query.query.QueryPackage#getSetMembershipPredicate_Set()
   * @model containment="true"
   * @generated
   */
  LogicalSet getSet();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.query.query.SetMembershipPredicate#getSet <em>Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set</em>' containment reference.
   * @see #getSet()
   * @generated
   */
  void setSet(LogicalSet value);

} // SetMembershipPredicate
