/*
 * generated by Xtext 2.32.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QueryStandaloneSetup extends QueryStandaloneSetupGenerated {

	public static void doSetup() {
		new QueryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
