/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query.impl;

import com.epistimis.uddl.query.query.CharacteristicBasis;
import com.epistimis.uddl.query.query.CharacteristicBasisSet;
import com.epistimis.uddl.query.query.QueryPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Characteristic Basis Set</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.impl.CharacteristicBasisSetImpl#getCharacteristicBasis <em>Characteristic Basis</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CharacteristicBasisSetImpl extends LogicalSetImpl implements CharacteristicBasisSet
{
  /**
   * The cached value of the '{@link #getCharacteristicBasis() <em>Characteristic Basis</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCharacteristicBasis()
   * @generated
   * @ordered
   */
  protected EList<CharacteristicBasis> characteristicBasis;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CharacteristicBasisSetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryPackage.Literals.CHARACTERISTIC_BASIS_SET;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CharacteristicBasis> getCharacteristicBasis()
  {
    if (characteristicBasis == null)
    {
      characteristicBasis = new EObjectContainmentEList<CharacteristicBasis>(CharacteristicBasis.class, this, QueryPackage.CHARACTERISTIC_BASIS_SET__CHARACTERISTIC_BASIS);
    }
    return characteristicBasis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryPackage.CHARACTERISTIC_BASIS_SET__CHARACTERISTIC_BASIS:
        return ((InternalEList<?>)getCharacteristicBasis()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryPackage.CHARACTERISTIC_BASIS_SET__CHARACTERISTIC_BASIS:
        return getCharacteristicBasis();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryPackage.CHARACTERISTIC_BASIS_SET__CHARACTERISTIC_BASIS:
        getCharacteristicBasis().clear();
        getCharacteristicBasis().addAll((Collection<? extends CharacteristicBasis>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryPackage.CHARACTERISTIC_BASIS_SET__CHARACTERISTIC_BASIS:
        getCharacteristicBasis().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryPackage.CHARACTERISTIC_BASIS_SET__CHARACTERISTIC_BASIS:
        return characteristicBasis != null && !characteristicBasis.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CharacteristicBasisSetImpl
