/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query.impl;

import com.epistimis.uddl.query.query.CharacteristicBasis;
import com.epistimis.uddl.query.query.QueryPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Characteristic Basis</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CharacteristicBasisImpl extends PredicateTermImpl implements CharacteristicBasis
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CharacteristicBasisImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryPackage.Literals.CHARACTERISTIC_BASIS;
  }

} //CharacteristicBasisImpl
