/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query.impl;

import com.epistimis.uddl.query.query.QueryPackage;
import com.epistimis.uddl.query.query.SelectedEntityCharacteristicWildcardReference;
import com.epistimis.uddl.query.query.SelectedEntityReference;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Selected Entity Characteristic Wildcard Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.query.query.impl.SelectedEntityCharacteristicWildcardReferenceImpl#getSelectedEntity <em>Selected Entity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SelectedEntityCharacteristicWildcardReferenceImpl extends ProjectedCharacteristicExpressionImpl implements SelectedEntityCharacteristicWildcardReference
{
  /**
   * The cached value of the '{@link #getSelectedEntity() <em>Selected Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSelectedEntity()
   * @generated
   * @ordered
   */
  protected SelectedEntityReference selectedEntity;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelectedEntityCharacteristicWildcardReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryPackage.Literals.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SelectedEntityReference getSelectedEntity()
  {
    return selectedEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSelectedEntity(SelectedEntityReference newSelectedEntity, NotificationChain msgs)
  {
    SelectedEntityReference oldSelectedEntity = selectedEntity;
    selectedEntity = newSelectedEntity;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY, oldSelectedEntity, newSelectedEntity);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSelectedEntity(SelectedEntityReference newSelectedEntity)
  {
    if (newSelectedEntity != selectedEntity)
    {
      NotificationChain msgs = null;
      if (selectedEntity != null)
        msgs = ((InternalEObject)selectedEntity).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY, null, msgs);
      if (newSelectedEntity != null)
        msgs = ((InternalEObject)newSelectedEntity).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY, null, msgs);
      msgs = basicSetSelectedEntity(newSelectedEntity, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY, newSelectedEntity, newSelectedEntity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY:
        return basicSetSelectedEntity(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY:
        return getSelectedEntity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY:
        setSelectedEntity((SelectedEntityReference)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY:
        setSelectedEntity((SelectedEntityReference)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryPackage.SELECTED_ENTITY_CHARACTERISTIC_WILDCARD_REFERENCE__SELECTED_ENTITY:
        return selectedEntity != null;
    }
    return super.eIsSet(featureID);
  }

} //SelectedEntityCharacteristicWildcardReferenceImpl
