/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query.impl;

import com.epistimis.uddl.query.query.QueryPackage;
import com.epistimis.uddl.query.query.UnqualifiedProjectedCharacteristicReferenceOrAlias;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Unqualified Projected Characteristic Reference Or Alias</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UnqualifiedProjectedCharacteristicReferenceOrAliasImpl extends ProjectedCharacteristicReferenceImpl implements UnqualifiedProjectedCharacteristicReferenceOrAlias
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnqualifiedProjectedCharacteristicReferenceOrAliasImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryPackage.Literals.UNQUALIFIED_PROJECTED_CHARACTERISTIC_REFERENCE_OR_ALIAS;
  }

} //UnqualifiedProjectedCharacteristicReferenceOrAliasImpl
