name: UDDLQuery Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and Publish Artifacts with Maven
      run: mvn clean install mkdir -p ${{ github.workspace }}/artifacts cp target/*.jar ${{ github.workspace }}/artifacts  
      # Publish artifacts 
    - name: Publish Artifacts 
      uses: actions/upload-artifact@v2 
      with: 
        name: my-artifacts 
        path: ${{ github.workspace }}/artifacts
