/*
 * generated by Xtext 2.32.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.ui;

import com.epistimis.uddl.query.ui.internal.QueryActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QueryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(QueryActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		QueryActivator activator = QueryActivator.getInstance();
		return activator != null ? activator.getInjector(QueryActivator.COM_EPISTIMIS_UDDL_QUERY_QUERY) : null;
	}

}
